name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Zmień na master, jeśli takiej nazwy używasz jako głównej

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps:deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      # Jeśli Twoja strona potrzebuje tylko plików z folderu www:
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './www' # Tutaj wskazujemy folder z plikami strony

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
